update alias function

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -1,10 +1,25 @@
+alias_if_program_exists() {
+  local ret='0'
+  command -v $1 >/dev/null 2>&1 || { local ret='1'; }
+  # if type nvim > /dev/null 2>&1; then
+  #   alias vi='nvim'
+  # fi
+
+  # fail on non-zero return value
+  if [ "$ret" -ne 0 ]; then
+    return 1
+  fi
+
+  alias $2=$1
+  return 0
+}
 
 if [ -f ~/.pyenv/py3/bin/activate ];then
   source ~/.pyenv/py3/bin/activate
 fi
-if [ -f $(which trash-put) ];then
-  alias rr='trash-put'
-fi
+
+alias_if_program_exists trash-put rr
+alias_if_program_exists nvim vi
 
 export TERM=xterm
 
@@ -27,9 +42,6 @@ source $HOME/.oh-my-zsh/oh-my-zsh.sh
 export LC_ALL="zh_CN.UTF-8"
 
 # alias
-if type nvim > /dev/null 2>&1; then
-  alias vi='nvim'
-fi
 alias pc='proxychains4'
 alias scpr='rsync -Pzv --exclude "logs" --rsh=ssh'
 # alias getpass='openssl rand -base64 20'
